### ISSUE TITLE
error cherch fo file :'(

### ISSUE THREAD

**Issue by FAROUKix** [Daxda/FTP-Miner#1]
└┼─#─┤▶ python FTP-Miner.py -s index.html
	-=[ Napalm ]=-
Traceback (most recent call last):
  File "FTP-Miner.py", line 122, in <module>
    main(args)
  File "FTP-Miner.py", line 92, in main
    function["func"](args).search()
  File "/root/Desktop/FTP-Miner-master/modules/napalm.py", line 50, in search
    self._session.get("http://www.searchftps.org/about")
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

+

how i can use FTP-miner.py ??

**Comment by FAROUKix** [comment]
@Daxda plz help me :'(

**Comment by Daxda** [comment]
This version is kinda deprecated, I'll publish my modified stuff soon-ish.

**Comment by FAROUKix** [comment]
ok tnx :)

**Comment by Daxda** [comment]
I published the modified version, let me know if this fixed your problem.

**Comment by FAROUKix** [comment]
ok :) tnx

**Comment by FAROUKix** [comment]
FIXED tnx :)
can i speak with you in facebook ?

**Comment by Daxda** [comment]
Glad I could help.
I don't use facebook.
